### ISSUE TITLE
Data models generation requirements

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/shape-up-process#42]
Part of #21

This issue's comments will contain all the discussions about which requirements for the library are to be expected. Once we agree on requirements they are added to this issue for later usage in an implementation phase. The requirements are to be stated as stories and sometimes wrapped in epics if there are commonalities between requirements. I would suggest we use a simplified version of requirement elicitation by doing the following tasks in chronological order (ticked off once done):

- [x] State user stories
- [x] State non-functional requirements (Optional, I am not sure if we have any to add here?)
- [x] Prioritize user stories (I would suggest we use use [MoSCoW](https://airfocus.com/glossary/what-is-moscow-prioritization/))

Common vocabolary:

<table>
<tr>
<th>
word(s)
</th>
<th>
meaning
</th>
</tr>

<tr>
<td>
properties
</td>
<td>
also known as variables
</td>
</tr>
<tr>
<td>
methods
</td>
<td>
also known as functions
</td>
</tr>
<tr>
<td>
users
</td>
<td>
Wrapped definition for template developers (React and Nunjucks) and developers in general.
</td>
</tr>
<tr>
<td>
Epics
</td>
<td>
A story which are to be broken into smaller stories.
</td>
</tr>
<tr>
<td>
Story, stories
</td>
<td>
Also called user-story, an expression of functionality to be implemented and stated on the form `As a < user > I want to < do something > so that < it provide some value >`. 
</td>
</tr>
</table>

## Epics
<table>
<tr>
<th>
Id
</th>
<th>
Description
</th>
</tr>

<tr>
<td>
#E1
</td>
<td>

As a **user** I want to **customize parts of the model generation** so that **I can control the output of the model generation**.

</td>
</tr>

<tr>
<td>
#E2
</td>
<td>

As a **user** I want to **provide different kind of inputs** so that **they can be standardized**.

</td>
</tr>

<tr>
<td>
#E3
</td>
<td>

As a **user** I want to **decide between different kind of model outputs** so that **I can use the data models in what ever context I need it in**.

</td>
</tr>
</table>

## Stories
<table>
<tr>
<th>
Id
</th>
<th>
Prioritization
</th>
<th>
Description
</th>
</tr>

<tr>
<td colspan="3">

### *Stories for Epic #E1*

</td>
</tr>

<tr>
<td>
#E1_S1
</td>
<td>
Could have
</td>
<td>

As a **user** I want to **specify a common supertype/basetype for some or all models generated** so that **I can use them under a common type**.

</td>
</tr>

<tr>
<td>
#E1_S2
</td>
<td>
Should have
</td>
<td>

As a **user** I want to **change the naming convention** so that **it complies with our company code naming policies**.

</td>
</tr>

<tr>
<td>
#E1_S3
</td>
<td>
Should have
</td>
<td>

As a **user** I want to **add some custom logic (method or variables) to some or all models** so that **so that I can standardize certain functionality**.

</td>
</tr>

<tr>
<td>
#E1_S4
</td>
<td>
Should have
</td>
<td>

As a **user** I want to **add custom dependencies** so that **they can be used in custom logic**.

</td>
</tr>

<tr>
<td>
#E1_S5
</td>
<td>
Should have
</td>
<td>

As a **user** I want to **add a custom method per property** so that **I can create encapsulation**.

</td>
</tr>

<tr>
<td>
#E1_S6
</td>
<td>
Should have
</td>
<td>

As a **user** I want to **add a custom constructor** so that **classes can be instanciated in different ways**.

</td>
</tr>

<tr>
<td>
#E1_S7
</td>
<td>
Should have
</td>
<td>

As a **user** I want to **add custom data validation to all or some variables** so that **I can influence the format**.

</td>
</tr>

<tr>
<td colspan="3">

### *Stories for Epic #E2*

</td>
</tr>

<tr>
<td>
#E2_S1
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to use JSON schema as input** so that **I can use both OpenAPI and AsyncAPI schemas**.

</td>
</tr>

<tr>
<td>
#E2_S2
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to use AsyncAPI as input** so that **so that I dont find all the schemas in my document**.

</td>
</tr>

<tr>
<td>
#E2_S3
</td>
<td>
Could have
</td>
<td>

As a **user** I want to **be able to use JSON as input** so that **so that I can dynamically generate models based on raw  messages**.

</td>
</tr>

<tr>
<td>
#E2_S4
</td>
<td>
Dont have
</td>
<td>

As a **user** I want to **provide any output from the model generation as input** so that **I can use existing data models to transform into another language**.

</td>
</tr>

<tr>
<td colspan="3">

### *Stories for Epic #E3*. We only include the ones we wish to implement ourself

</td>
</tr>

<tr>
<td>
#E3_S1
</td>
<td>
Could have
</td>
<td>

As a **user** I want to **be able to generate JSON Schema as output** so that **I can generate it based on my existing models**.

</td>
</tr>

<tr>
<td>
#E3_S2
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to generate TypeScript models as output** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S3
</td>
<td>
Could have
</td>
<td>

As a **user** I want to **be able to generate C++ models as output** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S4
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to generate C# models as output** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S5
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to generate Java models as output** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S6
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to generate Python models** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S7
</td>
<td>
Could have
</td>
<td>

As a **user** I want to **be able to generate Haskell models** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S8
</td>
<td>
Should have
</td>
<td>

As a **user** I want to **be able to generate Go models** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td colspan="3">

### *General stories*

</td>
</tr>

<tr>
<td>
#S1
</td>
<td>
Could have
</td>
<td>

As a **user** I want to **where possible, generate correct inheritance** so that **I can reduce dublicate code**.

</td>
</tr>

<tr>
<td>
#S2
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to create my own output model from scratch** so that **I can customize everything down to the last detail**.

</td>
</tr>

<tr>
<td>
#S3
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **be able to use the model generation in templates** so that **I dont have to worry about models but just the main logic**.

</td>
</tr>

<tr>
<td>
#S4
</td>
<td>
Must have
</td>
<td>

As a **user** I want to **use the model generation in libraries** so that **I can integrate it into my own code**.

</td>
</tr>

</table>

### Non-functional requirements
These are the non-functional requirements which the solution should adhere to:

1. Atleast a test coverage of 95% for the solution.
1. Include documentation regarding all the ways to customize the model generation.

**Comment by jonaslagoni** [comment]
Here are some of my initial requirement suggestions for the library. 



Common vocabolary:

<table>
<tr>
<th>
word(s)
</th>
<th>
meaning
</th>
</tr>


<tr>
<td>
properties
</td>
<td>
also known as variables
</td>
</tr>
<tr>
<td>
methods
</td>
<td>
also known as functions
</td>
</tr>
</table>



# Epics
<table>
<tr>
<th>
Id
</th>
<th>
Description
</th>
</tr>

<tr>
<td>
#E1
</td>
<td>

As a **user** I want to **customize parts of the model generation** so that **I can control the output of the model generation**.

</td>
</tr>


<tr>
<td>
#E2
</td>
<td>

As a **user** I want to **provide different kind of inputs** so that **they can be standardized**.

</td>
</tr>

<tr>
<td>
#E3
</td>
<td>

As a **user** I want to **decide between different kind of model outputs** so that **I can use the data models in what ever context I need it in**.

</td>
</tr>



</table>





# Stories


<table>
<tr>
<th>
Id
</th>
<th>
Description
</th>
</tr>
<tr>
<td colspan="3">

### *Stories for Epic #E1*

</td>
</tr>

<tr>
<td>
#E1_S1
</td>
<td>

As a **user** I want to **specify a common supertype/basetype for some or all models generated** so that **I can use them under a common type**.

</td>
</tr>


<tr>
<td>
#E1_S2
</td>
<td>

As a **user** I want to **change the naming convention** so that **it complies with our company code naming policies**.

</td>
</tr>


<tr>
<td>
#E1_S3
</td>
<td>

As a **user** I want to **add some custom logic (method or variables) to some or all models** so that **so that I can standardize certain functionality**.

</td>
</tr>


<tr>
<td>
#E1_S4
</td>
<td>

As a **user** I want to **add custom dependencies** so that **they can be used in custom logic**.

</td>
</tr>


<tr>
<td>
#E1_S5
</td>
<td>

As a **user** I want to **add a custom method per property** so that **I can create encapsulation**.

</td>
</tr>



<tr>
<td>
#E1_S6
</td>
<td>

As a **user** I want to **add a custom constructor** so that **classes can be instanciated in different ways**.

</td>
</tr>


<tr>
<td>
#E1_S7
</td>
<td>

As a **user** I want to **add custom data validation to all or some variables** so that **I can influence the format**.

</td>
</tr>

<tr>
<td colspan="3">

### *Stories for Epic #E2*

</td>
</tr>

<tr>
<td>
#E2_S1
</td>
<td>

As a **user** I want to **be able to use JSON schema as input** so that **I can use both OpenAPI and AsyncAPI schemas**.

</td>
</tr>


<tr>
<td>
#E2_S2
</td>
<td>

As a **user** I want to **be able to use AsyncAPI as input** so that **so that I dont find all the schemas in my document**.

</td>
</tr>


<tr>
<td>
#E2_S3
</td>
<td>

As a **user** I want to **be able to use JSON as input** so that **so that I can dynamically generate models based on raw  messages**.

</td>
</tr>


<tr>
<td>
#E2_S4
</td>
<td>

As a **user** I want to **provide any output from the model generation as input** so that **I can use existing data models to transform into another language**.

</td>
</tr>

<tr>
<td colspan="3">

### *Stories for Epic #E3*

</td>
</tr>

<tr>
<td>
#E3_S1
</td>
<td>

As a **user** I want to **be able to generate JSON Schema as output** so that **I can generate it based on my existing models**.

</td>
</tr>

<tr>
<td>
#E3_S2
</td>
<td>

As a **user** I want to **be able to generate TypeScript models as output** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S3
</td>
<td>

As a **user** I want to **be able to generate C++ models as output** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S4
</td>
<td>

As a **user** I want to **be able to generate C# models as output** so that **I can use them in my desired language**.

</td>
</tr>

<tr>
<td>
#E3_S5
</td>
<td>

As a **user** I want to **be able to generate Java models as output** so that **I can use them in my desired language**.

</td>
</tr>


<tr>
<td>
#E3_S6
</td>
<td>

As a **user** I want to **be able to generate Kafka schemaregistry model format** so that **I can add them to my schema regitry**.

</td>
</tr>


<tr>
<td>
#E3_S7
</td>
<td>

As a **user** I want to **be able to generate Python models** so that **I can use them in my desired language**.

</td>
</tr>


<tr>
<td>
#E3_S8
</td>
<td>

As a **user** I want to **be able to generate Haskell models** so that **I can use them in my desired language**.

</td>
</tr>


<tr>
<td colspan="3">

### *General stories*

</td>
</tr>


<tr>
<td>
#S1
</td>
<td>

As a **user** I want to **where possible, generate correct inheritance** so that **I can reduce dublicate code**.

</td>
</tr>

<tr>
<td>
#S2
</td>
<td>

As a **user** I want to **be able to create my own output model from scratch** so that **I can customize everything down to the last detail**.

</td>
</tr>

</table>


With the above user stories I am not only stating clear requirements, but also trying to push the limits of the definition for the model generation library and what is entails. 


What requirements do you see for the library? Is some of the ones I have stated confusing, out of scope, or do they not make sence lets discuss and start agreeing on requirements for the library so it can be added to the issue description.

**Comment by fmvilas** [comment]
> As a user I want to be able to use AsyncAPI as input so that so that I dont find all the schemas in my document.

What does it mean?

> As a user I want to be able to use JSON as input so that so that I can dynamically generate models based on raw messages.

Are you sure you want to provide such functionality in the first iteration? Also, what about Avro? I'm sure more people will request Avro support than this feature.

> As a user I want to be able to generate Kafka schemaregistry model format so that I can add them to my schema regitry.

I don't think we need this anymore. As long as you can generate Avro or JSON Schema it's compatible with Kafka Schema Registry. Also, in this section, I'm missing Go structs.

> As a user I want to be able to create my own output model from scratch so that I can customize everything down to the last detail.

Just an idea: use React 😄 

> As a user I want to be able to use the model generation in templates so that I dont have to worry about models but just the main logic.

THIS! This is probably the most important part for the user :)

---

Great job outlining all these requirements 👏 IMHO some of these are out of scope and some are nice-to-haves. More than grouping them by epics, I'd recommend you make an exercise of saying which ones are mandatory, which ones optional, and their priority in case you don't have time to implement everything. Or put it in a different way, define what's the minimum thing a user would find value with. Happy to help, of course.

**Comment by magicmatatjahu** [comment]
> As a user I want to provide any output from the model generation as input so that I can use existing data models to transform into another language.

As I understand this story, it is probably the hardest idea to implement, because to handle that we should create something like AST (abstract syntax tree) to read definition from one language, transform it to JSON Schema (here I only think, maybe this will be the easier way) and then render to another language - something like inverse enginering. Good idea but we should leave that for the end, because the user should generate the model from the asyncapi definition - in this case we will be generating asyncapi from the model, i.e. we will implement code-first instead of schema-first. Each additional language creates an additional interface/class to implement, and backward engineering itself isn't that easy. As I said it's good idea (I can say awesome), but we should leave it in first, second, third etc. iterations.

---

My list of priorities:
1. As a user I want to be able to create my own output model from scratch so that I can customize everything down to the last detail - why 1? Because for this we should create SDK, and then using SDK we should create first language implementation and then use this implementation in generator. 
2. As a user I want to be able to generate Java models as output so that I can use them in my desired language - why this language? Because Java will be probably the most used language in generator - see OpenAPI integration - Java is hegemon in this topic :)
3. As a user I want to be able to use AsyncAPI as input so that so that I dont find all the schemas in my document - without input data we have nothing to render
4. As a user I want to be able to use the model generation in templates so that I don't have to worry about models but just the main logic - probably most important think, but without first 3 we cannot achieve this.
5. All stories for Epic #E1
6. As a user I want to use the model generation in libraries so that I can integrate it into my own code.
7. As a user I want to be able to use JSON schema as input so that I can use both OpenAPI and AsyncAPI schemas.
8. Some languages from stories for Epic #E3 - I think that C#, JavaScript, Go, Python should have highest priority (of course Java has highest)
9. Some transformers from stories for Epic #E2
10. Rest of tasks

---

I think that the most difficult thing in this task (if someone starts to implement it) will be to do it right, i.e. not to do it wrong from the beginning, because then the client generation and perhaps the server generation etc. will be based on the model generation.

**Comment by jonaslagoni** [comment]
Thanks for the comments @fmvilas and @magicmatatjahu, as I see both of you jump directly into the prioritization phase I added a suggested workflow to follow in the issue. The idea was to state user stories we can see as becomming a reality in the future and not just state requirements for the first iteration. After user stories was agreed upon they are then prioritized using MosCoW (or any other prioritization method if you know a better one 😄).

So if you have any thoughts about what user stories are missing, wrongfully stated or should not even be there, lets discuss that first.


> What does it mean?

@fmvilas I want to provide the library with my parsed AsyncAPI document, or just a path to my AsyncAPI document where it would generate all of the models. This was a huge issue with QuickType that I could not pass my parsed payload, see https://github.com/jonaslagoni/asyncapi-quicktype-filter/issues/15.

> I don't think we need this anymore. As long as you can generate Avro or JSON Schema it's compatible with Kafka Schema Registry. Also, in this section, I'm missing Go struct

@fmvilas fair point. I have updated the comment where I removed this user story, I also clearified the output user story since including all the possible output models would be impossible we stick to the ones we plan to include our self.



> As I understand this story, it is probably the hardest idea to implement, because to handle that we should create something like AST (abstract syntax tree) to read definition from one language, transform it to JSON Schema (here I only think, maybe this will be the easier way) and then render to another language - something like inverse enginering

@magicmatatjahu yea exactly, agree with most of your prioritizations btw, but lets save them for later and discuss them there 😄

**Comment by jonaslagoni** [comment]
Me and @magicmatatjahu decided to propose 2 non-functional requirements to the solution as well. The following are the suggested requirements:
1. We have to reach a test coverage of 95% for the solution.
2. We have to include documentation regarding all the ways to customize the model generation.

Further we have added prioritations to all the stories. `Must have`s are things that have to be included in the 1st implementation and contains the very core of the data model generation. The following prioritizations can be included  subsequently in the next cycles.
