### ISSUE TITLE
Render missed parts in react-component that are showed in HTML template

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/shape-up-process#87]
We have list with missed parts in react-component that don't render (or render in wrong way):

- [x] It has a section of messages and schemas but it only shows the ones under `components`.
- [x] It's merging objects when it finds `allOf`, which is incorrect behavior.
- [x] It's not handling `additionalItems`.
- [x] It's not rendering `correlationId` asyncapi/html-template@d77c1c6
- [x] It's not rendering info that schema is Circular.
- [x] It cannot properly render type for combined schema `anyOf`, `allOf`, or `oneOf`.
- [x] It cannot render tags.
- [x] It's not rendering `extensions` https://github.com/asyncapi/html-template/blob/master/partials/schema-prop.html#L161
- [x] Adjust `bindings` component from [main branch](https://github.com/asyncapi/asyncapi-react/tree/master/library/src/containers/Bindings).

Ref: https://github.com/asyncapi/shape-up-process/issues/83

**Comment by derberg** [comment]
it in general should support spec with schemas having circular refs. In other words, should work with https://github.com/asyncapi/generator/blob/master/test/docs/dummy.yml

**Comment by magicmatatjahu** [comment]
@derberg Yes, I mentioned about it in this item `It's not rendering info that schema is Circular.`

**Comment by magicmatatjahu** [comment]
/progress 40 In https://github.com/asyncapi/asyncapi-react/pull/269 PR:

- handle circular properties,
- handle `additionalItems` and `additionalProperties`,
- handle combined schema `anyOf`, `allOf`, and `oneOf`.

**Comment by magicmatatjahu** [comment]
/progress 65 In asyncapi/asyncapi-react#276 PR:

- render `correlationId`,
- render `tags`,
- render all messages, not only under the `components` section,

**Comment by magicmatatjahu** [comment]
/progress 85 In asyncapi/asyncapi-react#280 PR:

- render `bindings`
- render `extensions`

**Comment by magicmatatjahu** [comment]
/progress 90 Currently, the component supports everything that has been mentioned. The only thing that still needs to be added to component is the side menu/navigation.

**Comment by magicmatatjahu** [comment]
/progress 100 Render side menu/navigation and missed examples for messages. Everything was added from HTML-Template. The skipped items will be added along with the https://github.com/asyncapi/shape-up-process/issues/86
